Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "the-lab-vagrant"
    google.google_json_key_location = "K:/The Lab/vagrant/vagrant-cloud/GCE/servicefile/servicefile.json"

    google.image_family = "ubuntu-2004-lts"
	
	google.zone = "europe-west1-b"

    override.ssh.username = "vagrantlenny"
    override.ssh.private_key_path = "C:/Users/vdwle/.ssh/google_compute_engine"
  end
  
  config.vm.provision:shell, inline: <<-SHELL
    apt update 
	apt upgrade -y
	apt install apache2 -y
  SHELL

end