# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set default provider to VMware Desktop
ENV['VAGRANT_DEFAULT_PROVIDER'] = "vmware_desktop"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"
  
  config.vm.provider "vmware_desktop" do |v|  
    v.vmx["memsize"] = "4096"  
    v.vmx["numvcpus"] = "3"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Update and upgrade
    apt-get update -y && apt-get upgrade -y
    # Install docker.io
    apt-get install docker.io -y
    usermod -aG docker vagrant
    # Install kubectl
    apt-get install -y apt-transport-https ca-certificates curl
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    apt-get update -y
    apt-get install -y kubectl
    # Install minikube and remove the deb package
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    dpkg -i minikube_latest_amd64.deb
    rm -f minikube_latest_amd64.deb
    # Reboot to re-evaluate group membership (docker group)
    reboot
  SHELL
end
