# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  
  config.vm.define "db" do |db|
    db.vm.boot_timeout= 600
    db.vm.box = "generic/ubuntu1804"
    db.vm.network "private_network", ip: "192.168.75.50" 

    
    
    db.vm.provider "vmware_workstation" do |vmware|
    vmware.vmx["memsize"] = '2048'
    vmware.vmx["displayname"] = "db"    
    end

  

    db.vm.provision "docker" do |d|
      d.run "mysql:5.7",
      args: "-e MYSQL_ROOT_PASSWORD=secretPass -e  MYSQL_USER=testuser -e MYSQL_PASSWORD=testPass -e MYSQL_DATABASE=appdb -p 3306:3306"      
    end
  end
  

  # config.vm.define "webapp" do |webapp|
  #   webapp.vm.boot_timeout= 600
  #   webapp.vm.box = "generic/ubuntu1804"
  #   webapp.vm.network "private_network", ip: "192.168.75.10"
  #   webapp.vm.synced_folder "./playbooks", "/vagrant/playbooks"    

  #   webapp.vm.provider "vmware_workstation" do |vmware|
  #     vmware.vmx["memsize"] = '2048'
  #     vmware.vmx["displayname"] = "webapp"      
  #   end
    
    
    
  #   webapp.vm.provision "shell",
  #     path: "scripts/python_install.sh"
     
  #   webapp.vm.provision "ansible_local" do |ansible|
  #     ansible.playbook = "./playbooks/dotnetapp_playbook.yml"

  #   end


  # end


 end

